services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: cryptoo_redis
    restart: always
    ports:
      - "6379:6379"

  app1:
    image: cryptoo-pricing
    container_name: cryptoo_app1
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"
    environment:
        - PORT=8081
        - ENVIRONMENT=docker
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PROT}/${POSTGRES_DB}?sslmode=disable
        - REDIS_ADDR=redis:6379
    volumes:
      - ./config/.env:/app/config/.env

  app2:
    image: cryptoo-pricing
    container_name: cryptoo_app2
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8082:8082"
    environment:
        - PORT=8082
        - ENVIRONMENT=docker
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PROT}/${POSTGRES_DB}?sslmode=disable
        - REDIS_ADDR=redis:6379
    volumes:
      - ./config/.env:/app/config/.env

volumes:
  db_data: