// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/dev-rever/cryptoo-pricing/internal/controller"
	"github.com/dev-rever/cryptoo-pricing/internal/db"
	"github.com/dev-rever/cryptoo-pricing/internal/middleware"
	"github.com/dev-rever/cryptoo-pricing/internal/router"
	"github.com/dev-rever/cryptoo-pricing/repository"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (*Application, error) {
	conn, err := db.ProvideDB(ctx)
	if err != nil {
		return nil, err
	}
	userRepo := repository.ProvideUserRepo(conn)
	userController := controller.ProvideUserCtrl(userRepo)
	handlerFunc := middleware.ProvideJWTMiddleware()
	engine := router.ProvideRouter(userController, handlerFunc)
	application := &Application{
		Router: engine,
		DB:     conn,
	}
	return application, nil
}

// wire.go:

var MiddlewareSet = wire.NewSet(middleware.ProvideJWTMiddleware)

type Application struct {
	Router *gin.Engine
	DB     *pgx.Conn
}
