// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/dev-rever/cryptoo-pricing/internal/controllers"
	"github.com/dev-rever/cryptoo-pricing/internal/db"
	"github.com/dev-rever/cryptoo-pricing/internal/middleware/jwt"
	"github.com/dev-rever/cryptoo-pricing/internal/middleware/mredis"
	"github.com/dev-rever/cryptoo-pricing/internal/router"
	"github.com/dev-rever/cryptoo-pricing/repositories"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (*Application, error) {
	conn, err := db.ProvideDB(ctx)
	if err != nil {
		return nil, err
	}
	user := repositories.ProvideUserRepo(conn)
	controllersUser := controllers.ProvideUserCtrl(user)
	wrap := mredis.ProvideMRedis()
	handlerFunc := jwt.ProvideJWTMiddleware()
	engine := router.ProvideRouter(controllersUser, wrap, handlerFunc)
	application := &Application{
		Router: engine,
		DB:     conn,
	}
	return application, nil
}

// wire.go:

var MiddlewareSet = wire.NewSet(jwt.ProvideJWTMiddleware, mredis.ProvideMRedis)

type Application struct {
	Router *router.Engine
	DB     *pgx.Conn
}
